package uz.pdp.eventorganizerbot.entity.enums;

public enum TgState {

    START,
    CHOOSING_MENU,
    ENTERING_EVENT_NAME, ENTERING_EVENT_DATE, ENTERING_EVENT_VENUE, ENTERING_EVENT_DESC, ENTERING_EVENT_MAX_PART, CHOOSING_EVENT_OPTIONS, GOING_BACK_TO_MAIN_MENU, CHOOSING_EVENT_MENU, CHOOSING_EVENT, CHOOSING_PAST_EVENT, GOING_BACK_TO_PAST_EVENTS,

}
